# rocgdb
[components.dbg."debug-tools/rocgdb/stage"]
[components.dev."debug-tools/rocgdb/stage"]
include = [
  "include/gdb/**",
  "share/locale/**",
  "share/rocgdb/python/**",
  "share/rocgdb/syscalls/**",
  "share/rocgdb/system-gdbinit/**"
]
[components.doc."debug-tools/rocgdb/stage"]
include = [
  "share/doc/**",
  "share/html/**",
  "share/info/**",
  "share/man/**"
]
[components.lib."debug-tools/rocgdb/stage"]
include = [
  "lib/**"
]
[components.run."debug-tools/rocgdb/stage"]
include = [
  "**/bin/**"
]
[components.test."debug-tools/rocgdb/stage"]
include = [
  "tests/**"
]
