[options]
unmatched_exclude = [
  "lib/rocm_sysdeps/share/locale/**",
  "lib/rocm_sysdeps/share/man/**",
]

# libpciaccess
[components.dev."third-party/sysdeps/linux/libpciaccess/build/stage"]
[components.lib."third-party/sysdeps/linux/libpciaccess/build/stage"]
