[options]
unmatched_exclude = [
  "lib/rocm_sysdeps/share/locale/**",
  "lib/rocm_sysdeps/share/man/**",
]

# NCurses
[components.dev."third-party/sysdeps/linux/ncurses/build/stage"]
include = [
  "lib/rocm_sysdeps/share/terminfo/**"
]
[components.doc."third-party/sysdeps/linux/ncurses/build/stage"]
[components.lib."third-party/sysdeps/linux/ncurses/build/stage"]
include = [
  "**/bin/*"
]
