[options]
unmatched_exclude = [
  "lib/rocm_sysdeps/share/locale/**",
  "lib/rocm_sysdeps/share/man/**",
]

# hwloc
[components.dev."third-party/sysdeps/linux/hwloc/build/stage"]
[components.doc."third-party/sysdeps/linux/hwloc/build/stage"]
[components.lib."third-party/sysdeps/linux/hwloc/build/stage"]
