# amdsmi
[components.dbg."core/amdsmi/stage"]
[components.dev."core/amdsmi/stage"]
[components.doc."core/amdsmi/stage"]
[components.lib."core/amdsmi/stage"]
include = [ "lib/**" ]
[components.run."core/amdsmi/stage"]
include = [
  "bin/**",
  "libexec/**",
  "share/amd_smi/**",
]
