# rocrtst
[components.dbg."core/rocrtst/stage"]
[components.dev."core/rocrtst/stage"]
[components.doc."core/rocrtst/stage"]
[components.run."core/rocrtst/stage"]
[components.test."core/rocrtst/stage"]
exclude = [
    "lib/rocrtst/lib/libhwloc.so*",
    "lib/rocrtst/lib/LICENSE",
]
